import { Context } from 'telegraf';
import { createChildLogger } from './logger.js';

const log = createChildLogger('telegram.utils');

/**
 * Splits text into safe chunks for Telegram message delivery (maximum 4096 chars per message).
 * Prefers splitting on paragraph boundaries (\n\n), then line breaks (\n), then spaces.
 */
export function splitTelegramMessage(text: string, maxLength: number = 4000): string[] {
  if (!text || text.length <= maxLength) {
    return [text];
  }

  const chunks: string[] = [];
  let remaining = text;

  while (remaining.length > 0) {
    if (remaining.length <= maxLength) {
      chunks.push(remaining);
      break;
    }

    // Try finding paragraph break
    let splitIdx = remaining.lastIndexOf('\n\n', maxLength);

    // If no paragraph break within limits, try single newline
    if (splitIdx === -1 || splitIdx < maxLength / 2) {
      splitIdx = remaining.lastIndexOf('\n', maxLength);
    }

    // If no newline, try space
    if (splitIdx === -1 || splitIdx < maxLength / 2) {
      splitIdx = remaining.lastIndexOf(' ', maxLength);
    }

    // If no good boundary, force hard break at maxLength
    if (splitIdx === -1) {
      splitIdx = maxLength;
    }

    const chunk = remaining.slice(0, splitIdx).trim();
    if (chunk) {
      chunks.push(chunk);
    }
    remaining = remaining.slice(splitIdx).trim();
  }

  return chunks;
}

/**
 * Escapes HTML characters for Telegram HTML parse mode.
 */
export function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

/**
 * Converts standard Markdown (such as generated by Gemini) into clean Telegram HTML format.
 * - Converts **bold** to <b>bold</b>
 * - Converts * bullet points to • unicode bullets (removes annoying asterisks)
 * - Converts # headers to <b>Header</b>
 * - Converts legacy *Sources:* or single-asterisk headings to <b>...</b>
 * - Preserves code blocks and inline code
 * - Preserves arithmetic multiplication (e.g. F = m * a)
 * - Auto-balances HTML tags to avoid Telegram 400 parse errors
 */
export function formatToTelegramHtml(markdown: string): string {
  if (!markdown) return '';

  // 1. Preserve code blocks (```code```)
  const codeBlocks: string[] = [];
  let text = markdown.replace(/```(?:[a-zA-Z0-9_-]+)?\n?([\s\S]*?)```/g, (_match, code) => {
    const placeholder = `\x00CB${codeBlocks.length}\x00`;
    codeBlocks.push(`<pre><code>${escapeHtml(code.trim())}</code></pre>`);
    return placeholder;
  });

  // 2. Preserve inline code (`code`)
  const inlineCodes: string[] = [];
  text = text.replace(/`([^`\n]+)`/g, (_match, code) => {
    const placeholder = `\x00IC${inlineCodes.length}\x00`;
    inlineCodes.push(`<code>${escapeHtml(code)}</code>`);
    return placeholder;
  });

  // 3. Escape HTML special characters in regular text
  text = escapeHtml(text);

  // 4. Convert markdown headers: # Title, ## Title, ### Title -> <b>Title</b>
  text = text.replace(/^#{1,6}\s+(.+)$/gm, '<b>$1</b>');

  // 5. Convert bullet points: lines starting with *, -, or + to unicode bullet •
  // Handles indented bullets as well
  text = text.replace(/^(\s*)[*\-+]\s+/gm, '$1• ');

  // 6. Convert bold italic: ***text*** or ___text___ -> <b><i>text</i></b>
  text = text.replace(/\*\*\*([^*]+?)\*\*\*/g, '<b><i>$1</i></b>');
  text = text.replace(/___([^_]+?)___/g, '<b><i>$1</i></b>');

  // 7. Convert bold: **text** or __text__ -> <b>text</b>
  text = text.replace(/\*\*([^*]+?)\*\*/g, '<b>$1</b>');
  text = text.replace(/__([^_]+?)__/g, '<b>$1</b>');

  // 8. Convert bold single asterisk (legacy Telegram markdown headings like *Sources:* or *Explanation:*):
  text = text.replace(/(^|[\s(])\*([^*\n]+?:)\*([\s).,!?;]|$)/g, '$1<b>$2</b>$3');

  // 9. Convert italic: *text* or _text_ (when bounded by non-word boundaries or whitespace)
  text = text.replace(/(^|[\s(])\*([^*\n]+?)\*([\s).,!?:;]|$)/g, '$1<i>$2</i>$3');
  text = text.replace(/(^|[\s(])_([^_\n]+?)_([\s).,!?:;]|$)/g, '$1<i>$2</i>$3');

  // 10. Clean up remaining dangling bold markers or lone asterisks at start of line
  text = text.replace(/^\s*\*\*([^*\n]+)$/gm, '<b>$1</b>');
  text = text.replace(/^(\s*)\*(\s*)/gm, '$1• ');
  text = text.replace(/\*\*/g, '');

  // 11. Restore code blocks and inline code
  for (let i = 0; i < codeBlocks.length; i++) {
    text = text.replace(`\x00CB${i}\x00`, codeBlocks[i]);
  }
  for (let i = 0; i < inlineCodes.length; i++) {
    text = text.replace(`\x00IC${i}\x00`, inlineCodes[i]);
  }

  // 12. Balance unclosed HTML tags to prevent Telegram entity parse errors
  text = balanceHtmlTags(text);

  return text;
}

/**
 * Strips markdown and asterisk formatting cleanly for plain-text fallback.
 * Keeps bullet symbols as clean unicode '•' and preserves arithmetic '*'.
 */
export function stripMarkdown(text: string): string {
  if (!text) return '';
  return text
    // Convert bullet asterisks to clean bullet symbol
    .replace(/^(\s*)[*\-+]\s+/gm, '$1• ')
    // Remove bold/italic markers
    .replace(/\*\*\*([^*]+?)\*\*\*/g, '$1')
    .replace(/\*\*([^*]+?)\*\*/g, '$1')
    .replace(/(^|[\s(])\*([^*\n]+?)\*([\s).,!?:;]|$)/g, '$1$2$3')
    .replace(/___([^_]+?)___/g, '$1')
    .replace(/__([^_]+?)__/g, '$1')
    .replace(/(^|[\s(])_([^_\n]+?)_([\s).,!?:;]|$)/g, '$1$2$3')
    // Remove markdown headers
    .replace(/^#{1,6}\s+/gm, '')
    // Clean up any remaining dangling double asterisks
    .replace(/\*\*/g, '')
    // Lone asterisk at line start
    .replace(/^(\s*)\*(\s*)/gm, '$1• ')
    .trim();
}

/**
 * Auto-balances unclosed HTML tags to guarantee valid Telegram HTML markup.
 */
function balanceHtmlTags(html: string): string {
  const openTags: string[] = [];
  const tagRegex = /<\/?([a-z0-9]+)[^>]*>/gi;
  let match;

  while ((match = tagRegex.exec(html)) !== null) {
    const fullTag = match[0];
    const tagName = match[1].toLowerCase();

    // Skip self-closing tags
    if (fullTag.endsWith('/>')) continue;

    if (fullTag.startsWith('</')) {
      const last = openTags[openTags.length - 1];
      if (last === tagName) {
        openTags.pop();
      }
    } else {
      openTags.push(tagName);
    }
  }

  while (openTags.length > 0) {
    const tag = openTags.pop();
    html += `</${tag}>`;
  }

  return html;
}

/**
 * Sends a message formatted as Telegram HTML with automatic fallback to clean text.
 */
export async function sendTelegramResponse(
  ctx: Context,
  markdownText: string,
  extra?: any
): Promise<void> {
  const parts = splitTelegramMessage(markdownText);
  for (const part of parts) {
    const html = formatToTelegramHtml(part);
    try {
      await ctx.reply(html, { parse_mode: 'HTML', ...extra });
    } catch (err: any) {
      log.warn({ err: err?.message }, 'Failed to send HTML formatted message, falling back to clean text.');
      await ctx.reply(stripMarkdown(part), extra);
    }
  }
}

/**
 * Edits an existing status message in-place or sends new messages safely using Telegram HTML.
 */
export async function editOrSendTelegramResponse(
  ctx: Context,
  statusMessageId: number | undefined,
  markdownText: string,
  extra?: any
): Promise<void> {
  const parts = splitTelegramMessage(markdownText);

  let replacedStatus = false;
  if (statusMessageId && parts.length === 1 && ctx.chat) {
    const html = formatToTelegramHtml(parts[0]);
    try {
      await ctx.telegram.editMessageText(
        ctx.chat.id,
        statusMessageId,
        undefined,
        html,
        { parse_mode: 'HTML', ...extra }
      );
      replacedStatus = true;
    } catch {
      try {
        await ctx.telegram.editMessageText(
          ctx.chat.id,
          statusMessageId,
          undefined,
          stripMarkdown(parts[0]),
          extra
        );
        replacedStatus = true;
      } catch {
        replacedStatus = false;
      }
    }
  }

  if (!replacedStatus) {
    if (statusMessageId && ctx.chat) {
      try {
        await ctx.telegram.deleteMessage(ctx.chat.id, statusMessageId);
      } catch {}
    }
    for (const part of parts) {
      const html = formatToTelegramHtml(part);
      try {
        await ctx.reply(html, { parse_mode: 'HTML', ...extra });
      } catch (err: any) {
        log.warn({ err: err?.message }, 'Failed to send HTML formatted chunk, falling back to clean text.');
        await ctx.reply(stripMarkdown(part), extra);
      }
    }
  }
}
